cia:
  adminRoles:
    - github-team:mozilla/cia
  externallyManaged: true
  repos:
    - github.com/armenzg/smart-scheduling:*
    - github.com/mozilla/cia-tasks:*
  workerPools:
    ci:
      owner: armenzg@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 1
      maxCapacity: 10
  secrets:
    garbage/foo: true
  grants:
    # all hooks
    - grant:
        - queue:scheduler-id:-
        - queue:create-task:low:proj-cia/*
        - auth:aws-s3:read-write:communitytc-bugbug/data/adr_cache/*
      to: hook-id:project-cia/*
    # smart-scheduling
    - grant:
        - secrets:get:project/cia/garbage/foo
      to: repo:github.com/armenzg/smart-scheduling:*
    # CI-A tasks
    - grant:
        - secrets:get:project/cia/garbage/foo
      to: repo:github.com/mozilla/cia-tasks:*
    # Grant a hook the capacity to fetch a secret
    - grant:
        - secrets:get:project/cia/garbage/foo
      to: hook-id:project-cia/hello-world
