deepspeech:
  adminRoles:
    - github-team:mozilla/research-machine-learning
    - github-team:coqui-ai/deepspeech-ci-owners
  repos:
    - github.com/mozilla/DeepSpeech:*
    - github.com/mozilla/tensorflow:*
    - github.com/coqui-ai/DeepSpeech:*
    - github.com/coqui-ai/tensorflow:*
  workerPools:
    ci:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 96
      machineType: "zones/{zone}/machineTypes/n1-standard-32"
    # Machine type for running Decision Task
    ci-decision-task:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 6
      machineType: "zones/{zone}/machineTypes/n2-standard-2"
    # BETA Machine type for running Decision Task
    ci-decision-task-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 6
      machineType: "zones/{zone}/machineTypes/n2-standard-2"
    # Machine type for running TensorFlow/Linux + CUDA builds
    ci-tf-build:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 8
      machineType: "zones/{zone}/machineTypes/n2-standard-48"
    # BETA Machine type for running TensorFlow/Linux + CUDA builds
    ci-tf-build-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 8
      machineType: "zones/{zone}/machineTypes/n2-standard-48"
    # Machine type for running DeepSpeech builds
    ci-ds-build:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 32
      machineType: "zones/{zone}/machineTypes/n2-highcpu-16"
    # BETA Machine type for running DeepSpeech builds
    ci-ds-build-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 32
      machineType: "zones/{zone}/machineTypes/n2-highcpu-16"
    # Machine type for running DeepSpeech tests
    ci-ds-tests:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 64
      machineType: "zones/{zone}/machineTypes/n2-highcpu-4"
    # BETA Machine type for running DeepSpeech tests
    ci-ds-tests-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 64
      machineType: "zones/{zone}/machineTypes/n2-highcpu-4"
    # Machine type for running memory-intensive DeepSpeech tests (Android)
    ci-ds-mem-tests:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 12
      machineType: "zones/{zone}/machineTypes/n2-highmem-4"
    # BETA Machine type for running memory-intensive DeepSpeech tests (Android)
    ci-ds-mem-tests-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 12
      machineType: "zones/{zone}/machineTypes/n2-highmem-4"
    ds-macos-tf-build:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: generic-worker
      cloud: static
      lifecycle:
        reregistrationTimeout: 2592000 # 30 days
    ds-macos-tf-build-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: generic-worker
      cloud: static
      lifecycle:
        reregistrationTimeout: 2592000 # 30 days
    ds-macos-ds-build:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: generic-worker
      cloud: static
      lifecycle:
        reregistrationTimeout: 2592000 # 30 days
    ds-macos-ds-build-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: generic-worker
      cloud: static
      lifecycle:
        reregistrationTimeout: 2592000 # 30 days
    ds-macos-ds-tests:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: generic-worker
      cloud: static
      lifecycle:
        reregistrationTimeout: 2592000 # 30 days
    ds-macos-ds-tests-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: generic-worker
      cloud: static
      lifecycle:
        reregistrationTimeout: 2592000 # 30 days
    win:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: deepspeech-win2012r2
      cloud: aws
      instanceTypes:
        m5d.2xlarge: 1
      maxCapacity: 16
    win-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: deepspeech-win2012r2-b
      cloud: aws
      instanceTypes:
        m5d.2xlarge: 1
      maxCapacity: 16
    win-gpu:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: deepspeech-win2012r2-gpu
      cloud: aws
      instanceTypes:
        g3s.xlarge: 1
      maxCapacity: 4
    win-gpu-b:
      owner: taskcluster@deep-speech.org
      emailOnError: false
      imageset: deepspeech-win2012r2-gpu-b
      cloud: aws
      instanceTypes:
        g3s.xlarge: 1
      maxCapacity: 4
  clients:
    worker/rpi3bp-1:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-2:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-3:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-4:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-5:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-6:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/lepotato-1:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-2:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-3:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-4:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-5:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-6:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    # Machine type for running TensorFlow builds
    worker/macos-tf-build:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-tf-build-*
        - assume:worker-pool:proj-deepspeech/ds-macos-tf-build
    # BETA Machine type for running TensorFlow builds
    worker/macos-tf-build-b:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-tf-build-b-*
        - assume:worker-pool:proj-deepspeech/ds-macos-tf-build-b
    # Machine type for running DeepSpeech builds
    worker/macos-ds-build:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-ds-build-*
        - assume:worker-pool:proj-deepspeech/ds-macos-ds-build
    # BETA Machine type for running DeepSpeech builds
    worker/macos-ds-build-b:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-ds-build-b-*
        - assume:worker-pool:proj-deepspeech/ds-macos-ds-build-b
    # Machine type for running DeepSpeech tests
    worker/macos-ds-tests:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-ds-tests-*
        - assume:worker-pool:proj-deepspeech/ds-macos-ds-tests
    # BETA Machine type for running DeepSpeech tests
    worker/macos-ds-tests-b:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-ds-tests-b-*
        - assume:worker-pool:proj-deepspeech/ds-macos-ds-tests-b
    worker/pkguploader:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-scriptworker-*
        - assume:worker-pool:proj-deepspeech/ds-scriptworker
  grants:
    - grant:
        - queue:create-task:highest:proj-deepspeech/*
        # decision task:
        # https://github.com/mozilla/tensorflow/blob/master/tc-schedule.sh
        # =>
        # https://github.com/lissyx/taskcluster-github-decision/blob/master/tc-decision.py
        - queue:scheduler-id:taskcluster-github
        - queue:route:index.project.deepspeech.*
        - index:insert-task:project.deepspeech.*
        - queue:route:notify.irc-channel.*
        - generic-worker:cache:deepspeech-*
        - docker-worker:capability:device:kvm
      to:
        - repo:github.com/mozilla/DeepSpeech:*
        - repo:github.com/mozilla/tensorflow:*
        - repo:github.com/coqui-ai/DeepSpeech:*
        - repo:github.com/coqui-ai/tensorflow:*
    - grant:
        - generic-worker:allow-rdp:proj-deepspeech/*
        - generic-worker:os-group:proj-deepspeech/*
      to:
        - project-admin:deepspeech
  secrets:
    ssh-keys/deepspeech-win: true
    ssh-keys/deepspeech-win-b: true
    ssh-keys/deepspeech-win-gpu: true
    ssh-keys/deepspeech-win-gpu-b: true
