fuzzing:
  adminRoles:
    - github-team:MozillaSecurity/tc-admin
  repos:
    - github.com/MozillaSecurity/*
  secrets:
    codecov-fuzzfetch: true
    codecov-fuzzmanager: true
    credstash-aws-auth: true
    deploy-bearspray: true
    deploy-fuzzing-tc-config: true
    deploy-octo-private: true
    docker-hub: true
    pypi: true
    decision: true
  workerPools:
    ci:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
      workerConfig:
        dockerConfig:
          allowPrivileged: true
    decision:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
    generic-worker-ubuntu-18-04-podman:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: generic-worker-ubuntu-18-04-podman
      cloud: aws
      minCapacity: 0
      maxCapacity: 10

  hooks:
    decision:
      description: Hook to trigger the Fuzzing decision task
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: true
      schedule:
        - "0 0 */1 * * *"
      task:
        provisionerId: proj-fuzzing
        workerType: decision
        scopes:
          - secrets:get:project/fuzzing/decision
          - queue:scheduler-id:-
          - queue:create-task:highest:proj-fuzzing/decision
        payload:
          image: mozillasecurity/fuzzing-tc:latest
          features:
            taskclusterProxy: true
          env:
            TASKCLUSTER_SECRET: project/fuzzing/decision
          maxRunTime: 1200
        metadata:
          name: Fuzzing decision task
          description: Create fuzzing task on Mozilla Firefox builds
          owner: fuzzing+taskcluster@mozilla.com
          source: https://github.com/mozillasecurity/fuzzing-tc-config

  grants:
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - secrets:get:project/fuzzing/deploy-*
        - secrets:get:project/fuzzing/codecov-*
        - secrets:get:project/fuzzing/pypi
        - secrets:get:project/fuzzing/ci-*
      to:
        - repo:github.com/MozillaSecurity/*
    - grant:
        - docker-worker:capability:privileged
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc:*
    - grant:
        - secrets:get:project/fuzzing/deploy-fuzzing-tc-config
        - secrets:get:project/fuzzing/decision
        - queue:scheduler-id:-
        - queue:create-task:highest:proj-fuzzing/decision
      to: hook-id:project-fuzzing/decision
