fuzzing:
  adminRoles:
    - github-team:MozillaSecurity/tc-admin
  externallyManaged: true # Fuzzing hooks are deployed through another repo
  repos:
    - github.com/MozillaSecurity/*
  workerPools:
    bugmon-monitor:
      owner: jkratzer@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 5
    bugmon-processor:
      owner: jkratzer@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
    ci:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 20
      workerConfig:
        dockerConfig:
          allowPrivileged: true
    ci-windows:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: generic-worker-win2012r2
      cloud: aws
      minCapacity: 0
      maxCapacity: 10
    grizzly-reduce-monitor:
      owner: truber@mozilla.com
      emailOnError: true
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 5
    grizzly-reduce-worker:
      owner: truber@mozilla.com
      emailOnError: true
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 20
  hooks:
    domino-web-tests:
      description: Domino Web Tests trigger
      owner: jkratzer@mozilla.com
      emailOnError: true
      bindings:
        - exchange: exchange/taskcluster-github/v1/push
          routingKeyPattern: primary.MozillaSecurity.domino
        - exchange: exchange/taskcluster-github/v1/push
          routingKeyPattern: primary.MozillaSecurity.GrIDL
      task:
        provisionerId: proj-fuzzing
        workerType: ci
        payload:
          image:
            type: indexed-image
            path: public/domino-web-tests.tar.zst
            namespace: project.fuzzing.orion.domino-web-tests.master
          features:
            taskclusterProxy: true
          maxRunTime: 3600
          env:
            ACTION: trigger
        metadata:
          name: Domino Web Tests
          description: Domino Web Tests
          owner: jkratzer@mozilla.com
          source: 'https://github.com/MozillaSecurity/domino-web-tests'
        expires:
          $fromNow: 3 months
        deadline:
          $fromNow: 6 hours
        scopes:
          - queue:create-task:highest:proj-fuzzing/ci
          - secrets:get:project/fuzzing/deploy-domino-web-tests
          - secrets:get:project/fuzzing/deploy-domino
          - secrets:get:project/fuzzing/deploy-gridl
          - secrets:get:project/fuzzing/deploy-octo-private
      triggerSchema:
        type: object
        properties:
          branch:
            type: string
            default: master
        additionalProperties: true
    grizzly-reduce-monitor:
      description: Hook for triggering Grizzly reduce monitor tasks
      owner: truber@mozilla.com
      emailOnError: true
      task:
        provisionerId: proj-fuzzing
        schedulerId: fuzzing
        workerType: grizzly-reduce-monitor
        payload:
          image:
            type: indexed-image
            path: public/grizzly-reduce-monitor.tar.zst
            namespace: project.fuzzing.orion.grizzly-reduce-monitor.master
          features:
            taskclusterProxy: true
          maxRunTime: 3600
          command:
            - '/usr/bin/grizzly-reduce-tc-monitor'
          artifacts:
            project/fuzzing/private/logs:
              path: /logs/
              type: directory
        metadata:
          name: grizzly-reduce-monitor
          description: Create grizzly testcases reduction tasks
          owner: truber@mozilla.com
          source: 'https://github.com/MozillaSecurity/grizzly'
        expires:
          $fromNow: 2 weeks
        deadline:
          $fromNow: 3 hours
        scopes:
          - docker-worker:capability:device:hostSharedMemory
          - docker-worker:capability:device:loopbackAudio
          - queue:create-task:highest:proj-fuzzing/grizzly-reduce-worker
          - queue:route:notify.email.truber@mozilla.com.on-failed
          - queue:scheduler-id:fuzzing
          - secrets:get:project/fuzzing/deploy-bearspray
          - secrets:get:project/fuzzing/deploy-grizzly-private
          - secrets:get:project/fuzzing/fuzzmanagerconf
          - secrets:get:project/fuzzing/google-logging-creds
          - secrets:get:project/fuzzing/grizzly-reduce-tool-list
        routes:
          - notify.email.truber@mozilla.com.on-failed
      schedule:
        - "0 */2 * * *"
    grizzly-reduce-reset-error:
      description: Hook for resetting Grizzly reduce tasks on error
      owner: truber@mozilla.com
      emailOnError: true
      bindings:
        - exchange: exchange/taskcluster-queue/v1/task-exception
          routingKeyPattern: primary.#.grizzly-reduce-worker.fuzzing.#
        - exchange: exchange/taskcluster-queue/v1/task-failed
          routingKeyPattern: primary.#.grizzly-reduce-worker.fuzzing.#
      task:
        provisionerId: proj-fuzzing
        schedulerId: fuzzing
        workerType: grizzly-reduce-monitor
        payload:
          image:
            type: indexed-image
            path: public/grizzly-reduce-monitor.tar.zst
            namespace: project.fuzzing.orion.grizzly-reduce-monitor.master
          features:
            taskclusterProxy: true
          maxRunTime: 600
          command:
            - '/usr/bin/grizzly-reduce-tc-update'
            - '--crash-from-reduce-task'
            - '${payload.status.taskId}'
            - '--quality'
            - '5'
            - '--only-if-quality'
            - '4'
          artifacts:
            project/fuzzing/private/logs:
              path: /logs/
              type: directory
        metadata:
          name: grizzly-reduce-monitor
          description: Reset grizzly testcase after failed reduction
          owner: truber@mozilla.com
          source: 'https://github.com/MozillaSecurity/grizzly'
        expires:
          $fromNow: 2 weeks
        deadline:
          $fromNow: 1 hour
        scopes:
          - queue:route:notify.email.truber@mozilla.com.on-failed
          - queue:scheduler-id:fuzzing
          - secrets:get:project/fuzzing/fuzzmanagerconf
        routes:
          - notify.email.truber@mozilla.com.on-failed
    bugmon:
      description: Hook for triggering bugmon monitor tasks
      owner: jkratzer@mozilla.com
      emailOnError: true
      task:
        provisionerId: proj-fuzzing
        workerType: bugmon-monitor
        payload:
          image:
            type: indexed-image
            path: public/bugmon.tar.zst
            namespace: project.fuzzing.orion.bugmon.master
          features:
            taskclusterProxy: true
          maxRunTime: 10800
          env:
            BUG_ACTION: monitor
          artifacts:
            project/fuzzing/bugmon:
              path: /bugmon-artifacts
              type: directory
        metadata:
          name: bugmon
          description: Hook for triggering bugmon monitor tasks
          owner: jkratzer@mozilla.com
          source: 'https://github.com/MozillaSecurity/bugmon'
        expires:
          $fromNow: 3 months
        deadline:
          $fromNow: 6 hours
        scopes:
          - docker-worker:capability:device:hostSharedMemory
          - docker-worker:capability:device:loopbackAudio
          - docker-worker:capability:privileged
          - queue:create-task:highest:proj-fuzzing/bugmon-monitor
          - queue:create-task:highest:proj-fuzzing/bugmon-processor
          - queue:get-artifact:project/fuzzing/bugmon/*
          - queue:route:notify.email.jkratzer@mozilla.com.on-failed
          - queue:scheduler-id:-
          - secrets:get:project/fuzzing/bz-api-key
        routes:
          - notify.email.jkratzer@mozilla.com.on-failed
      schedule:
        - "0 */8 * * *"
    js-tests-distiller:
      description: Hook for distilling JS tests for fuzzing
      owner: fuzzing@mozilla.com
      emailOnError: true
      task:
        provisionerId: proj-fuzzing
        schedulerId: fuzzing
        workerType: ci
        payload:
          features:
            taskclusterProxy: true
          image:
            type: indexed-image
            namespace: project.fuzzing.orion.js-tests-distiller.master
            path: public/js-tests-distiller.tar.zst
          maxRunTime: 10800
          artifacts:
            public/tests.zip:
              path: /home/ubuntu/output/jstests-distilled.zip
              type: file
        metadata:
          name: js-tests-distiller
          description: Hook for distilling JS tests for fuzzing
          owner: fuzzing@mozilla.com
          source: 'https://github.com/MozillaSecurity'
        expires:
          $fromNow: 4 weeks
        deadline:
          $fromNow: 12 hours
        scopes:
          - queue:route:index.project.fuzzing.js-tests-distiller.latest
          - queue:route:notify.email.fuzzing@mozilla.com.on-failed
          - queue:scheduler-id:fuzzing
          - secrets:get:project/fuzzing/deploy-langfuzz
        routes:
          - index.project.fuzzing.js-tests-distiller.latest
          - notify.email.fuzzing@mozilla.com.on-failed
      schedule:
        - "0 0 * * *"
    coverage-revision:
      description: Hook for pinning m-c revision for periodic fuzzing coverage tasks
      owner: fuzzing@mozilla.com
      emailOnError: true
      task:
        provisionerId: proj-fuzzing
        schedulerId: fuzzing
        workerType: ci
        payload:
          image:
            type: indexed-image
            namespace: project.fuzzing.orion.coverage-revision.master
            path: public/coverage-revision.tar.zst
          maxRunTime: 600
          artifacts:
            public/coverage-revision.txt:
              path: /coverage-revision.txt
              type: file
        metadata:
          name: coverage-revision
          description: Hook for pinning m-c revision for periodic fuzzing coverage tasks
          owner: fuzzing@mozilla.com
          source: 'https://github.com/MozillaSecurity'
        expires:
          $fromNow: 4 weeks
        deadline:
          $fromNow: 3 hours
        scopes:
          - queue:route:index.project.fuzzing.coverage-revision.latest
          - queue:route:notify.email.fuzzing@mozilla.com.on-failed
          - queue:scheduler-id:fuzzing
        routes:
          - index.project.fuzzing.coverage-revision.latest
          - notify.email.fuzzing@mozilla.com.on-failed
      schedule:
        - "0 0 * * 1"
    gr-css:
      description: Hook for updating gr.css grammar
      owner: jkratzer@mozilla.com
      emailOnError: true
      task:
        provisionerId: proj-fuzzing
        workerType: ci
        payload:
          image:
            type: indexed-image
            path: public/gr-css-reports.tar.zst
            namespace: project.fuzzing.orion.gr-css-reports.master
          features:
            taskclusterProxy: true
          maxRunTime: 10800
          artifacts:
            project/fuzzing/gr-css:
              path: /live.log
              type: file
        metadata:
          name: gr-css
          description: Hook for updating gr.css grammar
          owner: jkratzer@mozilla.com
          source: 'https://github.com/MozillaSecurity/gr.css.reports'
        expires:
          $fromNow: 1 months
        deadline:
          $fromNow: 6 hours
        scopes:
          - docker-worker:capability:device:hostSharedMemory
          - docker-worker:capability:device:loopbackAudio
          - docker-worker:capability:privileged
          - queue:get-artifact:project/fuzzing/gr-css/*
          - queue:route:notify.email.jkratzer@mozilla.com.on-failed
          - queue:scheduler-id:-
          - secrets:get:project/fuzzing/deploy-gr-css
          - secrets:get:project/fuzzing/deploy-gr-css-generator
          - secrets:get:project/fuzzing/deploy-gr-css-reports
          - secrets:get:project/fuzzing/deploy-octo-private
          - secrets:get:project/fuzzing/deploy-npm
          - secrets:get:project/fuzzing/ci-git-token
        routes:
          - notify.email.jkratzer@mozilla.com.on-failed
      schedule:
        - "0 10 * * *"
  grants:
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - queue:create-task:highest:proj-fuzzing/ci-*
        - secrets:get:project/fuzzing/deploy-*
        - secrets:get:project/fuzzing/codecov-*
        - secrets:get:project/fuzzing/pypi-*
        - secrets:get:project/fuzzing/ci-*
      to:
        - repo:github.com/MozillaSecurity/*
    - grant:
        - queue:scheduler-id:fuzzing
      to:
        - hook-id:project-fuzzing/*
        - repo:github.com/MozillaSecurity/*
    - grant:
        - docker-worker:capability:privileged
        - queue:route:index.project.fuzzing.config.*
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc:*
    - grant:
        - secrets:get:project/fuzzing/decision
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc-config:*
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - queue:scheduler-id:-
        - secrets:get:project/fuzzing/deploy-domino
        - secrets:get:project/fuzzing/deploy-domino-web-tests
        - secrets:get:project/fuzzing/deploy-gridl
        - secrets:get:project/fuzzing/deploy-octo-private
      to:
        - hook-id:project-fuzzing/domino-web-tests
    # fuzzing-tc-config code on master can run tc-admin apply to manage worker pools
    - grant:
        - assume:hook-id:project-fuzzing/*
        - auth:create-role:hook-id:project-fuzzing/*
        - auth:update-role:hook-id:project-fuzzing/*
        - auth:delete-role:hook-id:project-fuzzing/*
        - docker-worker:capability:device:hostSharedMemory
        - docker-worker:capability:device:loopbackAudio
        - docker-worker:capability:privileged
        - hooks:modify-hook:project-fuzzing/*
        - hooks:trigger-hook:project-fuzzing/*
        - queue:create-task:highest:proj-fuzzing/*
        - queue:scheduler-id:-
        - queue:cancel-task:-/*
        - secrets:get:project/fuzzing/*
        - worker-manager:manage-worker-pool:proj-fuzzing/*
        - worker-manager:provider:community-tc-workers-*
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc-config:branch:master
    - grant:
        - docker-worker:capability:device:hostSharedMemory
        - docker-worker:capability:device:loopbackAudio
        - docker-worker:capability:privileged
        - queue:create-task:highest:proj-fuzzing/bugmon-monitor
        - queue:create-task:highest:proj-fuzzing/bugmon-processor
        - queue:get-artifact:project/fuzzing/bugmon/*
        - queue:route:notify.email.jkratzer@mozilla.com.on-failed
        - queue:scheduler-id:-
        - secrets:get:project/fuzzing/bz-api-key
      to:
        - hook-id:project-fuzzing/bugmon
    - grant:
        - docker-worker:capability:device:hostSharedMemory
        - docker-worker:capability:device:loopbackAudio
        - queue:create-task:highest:proj-fuzzing/grizzly-reduce-worker
        - secrets:get:project/fuzzing/deploy-bearspray
        - secrets:get:project/fuzzing/deploy-grizzly-private
        - secrets:get:project/fuzzing/google-logging-creds
        - secrets:get:project/fuzzing/grizzly-reduce-tool-list
      to:
        - hook-id:project-fuzzing/grizzly-reduce-monitor
    - grant:
        - queue:create-task:highest:proj-fuzzing/grizzly-reduce-monitor
        - queue:route:notify.email.truber@mozilla.com.on-failed
        - secrets:get:project/fuzzing/fuzzmanagerconf
      to:
        - hook-id:project-fuzzing/grizzly-reduce-reset-error
        - hook-id:project-fuzzing/grizzly-reduce-monitor
    - grant:
        - docker-worker:capability:privileged
        - queue:route:index.project.fuzzing.orion.*
        - secrets:get:project/fuzzing/docker-hub
      to:
        - repo:github.com/MozillaSecurity/orion:*
    - grant:
        - docker-worker:capability:privileged
        - queue:route:index.project.fuzzing.reduce-monitor.*
      to:
        - repo:github.com/MozillaSecurity/grizzly-reduce-tc:*
    - grant:
        - generic-worker:allow-rdp:proj-fuzzing/*
        - queue:cancel-task:fuzzing/*
      to:
        - project-admin:fuzzing
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - queue:route:notify.email.fuzzing@mozilla.com.on-failed
        - queue:route:index.project.fuzzing.js-tests-distiller.*
        - secrets:get:project/fuzzing/deploy-langfuzz
      to:
        - hook-id:project-fuzzing/js-tests-distiller
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - queue:route:notify.email.fuzzing@mozilla.com.on-failed
        - queue:route:index.project.fuzzing.coverage-revision.*
      to:
        - hook-id:project-fuzzing/coverage-revision
    - grant:
        - docker-worker:capability:device:hostSharedMemory
        - docker-worker:capability:device:loopbackAudio
        - docker-worker:capability:privileged
        - queue:create-task:highest:proj-fuzzing/ci
        - queue:get-artifact:project/fuzzing/gr-css/*
        - queue:route:notify.email.jkratzer@mozilla.com.on-failed
        - queue:scheduler-id:-
        - secrets:get:project/fuzzing/ci-git-token
        - secrets:get:project/fuzzing/deploy-gr-css
        - secrets:get:project/fuzzing/deploy-gr-css-generator
        - secrets:get:project/fuzzing/deploy-gr-css-reports
        - secrets:get:project/fuzzing/deploy-octo-private
        - secrets:get:project/fuzzing/deploy-npm
      to:
        - hook-id:project-fuzzing/gr-css
