fuzzing:
  adminRoles:
    - github-team:MozillaSecurity/tc-admin
  externallyManaged: true # Fuzzing hooks are deployed through another repo
  repos:
    - github.com/MozillaSecurity/*
  workerPools:
    bugmon-monitor:
      owner: jkratzer@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 5
    bugmon-processor:
      owner: jkratzer@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
    ci:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
    grizzly-reduce:
      owner: fuzzing+grizzly@mozilla.com
      emailOnError: true
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 20
  hooks:
    domino-web-tests:
      description: Domino Web Tests trigger
      owner: jkratzer@mozilla.com
      emailOnError: true
      bindings:
        - exchange: exchange/taskcluster-github/v1/push
          routingKeyPattern: primary.MozillaSecurity.domino
        - exchange: exchange/taskcluster-github/v1/push
          routingKeyPattern: primary.MozillaSecurity.GrIDL
      task:
        provisionerId: proj-fuzzing
        workerType: ci
        payload:
          image: 'mozillasecurity/domino-web-tests:latest'
          features:
            taskclusterProxy: true
          maxRunTime: 3600
          env:
            ACTION: trigger
        metadata:
          name: Domino Web Tests
          description: Domino Web Tests
          owner: jkratzer@mozilla.com
          source: 'https://github.com/MozillaSecurity/domino-web-tests'
        expires:
          $fromNow: 3 months
        deadline:
          $fromNow: 6 hours
        scopes:
          - queue:create-task:highest:proj-fuzzing/ci
          - secrets:get:project/fuzzing/deploy-domino-web-tests
          - secrets:get:project/fuzzing/deploy-domino
          - secrets:get:project/fuzzing/deploy-gridl
          - secrets:get:project/fuzzing/deploy-octo-private
      triggerSchema:
        type: object
        properties:
          branch:
            type: string
            default: master
        additionalProperties: true
    bugmon:
      description: Hook for triggering bugmon monitor tasks
      owner: jkratzer@mozilla.com
      emailOnError: true
      task:
        provisionerId: proj-fuzzing
        workerType: bugmon-monitor
        payload:
          image: 'mozillasecurity/bugmon:latest'
          features:
            taskclusterProxy: true
          maxRunTime: 3600
          env:
            BUG_ACTION: monitor
          artifacts:
            project/fuzzing/bugmon:
              path: /bugmon-artifacts
              type: directory
        metadata:
          name: bugmon
          description: Hook for triggering bugmon monitor tasks
          owner: jkratzer@mozilla.com
          source: 'https://github.com/MozillaSecurity/bugmon'
        expires:
          $fromNow: 3 months
        deadline:
          $fromNow: 6 hours
        scopes:
          - docker-worker:capability:device:hostSharedMemory
          - docker-worker:capability:device:loopbackAudio
          - docker-worker:capability:privileged
          - queue:create-task:highest:proj-fuzzing/bugmon-monitor
          - queue:create-task:highest:proj-fuzzing/bugmon-processor
          - queue:get-artifact:project/fuzzing/bugmon/*
          - queue:route:notify.email.jkratzer@mozilla.com.on-failed
          - queue:scheduler-id:-
          - secrets:get:project/fuzzing/bz-api-key
      routes:
        - notify.email.jkratzer@mozilla.com.on-failed
      schedule:
        - "0 */8 * * *"
  grants:
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - secrets:get:project/fuzzing/deploy-*
        - secrets:get:project/fuzzing/codecov-*
        - secrets:get:project/fuzzing/pypi
        - secrets:get:project/fuzzing/ci-*
      to:
        - repo:github.com/MozillaSecurity/*
    - grant:
        - docker-worker:capability:privileged
        - queue:route:index.project.fuzzing.config.*
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc:*
    - grant:
        - secrets:get:project/fuzzing/decision
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc-config:*
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - queue:scheduler-id:-
        - secrets:get:project/fuzzing/deploy-domino
        - secrets:get:project/fuzzing/deploy-domino-web-tests
        - secrets:get:project/fuzzing/deploy-gridl
        - secrets:get:project/fuzzing/deploy-octo-private
      to:
        - hook-id:project-fuzzing/domino-web-tests
    # fuzzing-tc-config code on master can run tc-admin apply to manage worker pools
    - grant:
        - assume:hook-id:project-fuzzing/*
        - auth:create-role:hook-id:project-fuzzing/*
        - auth:update-role:hook-id:project-fuzzing/*
        - auth:delete-role:hook-id:project-fuzzing/*
        - docker-worker:capability:device:hostSharedMemory
        - docker-worker:capability:device:loopbackAudio
        - docker-worker:capability:privileged
        - hooks:modify-hook:project-fuzzing/*
        - hooks:trigger-hook:project-fuzzing/*
        - queue:create-task:highest:proj-fuzzing/*
        - queue:scheduler-id:-
        - queue:cancel-task:-/*
        - secrets:get:project/fuzzing/*
        - worker-manager:manage-worker-pool:proj-fuzzing/*
        - worker-manager:provider:community-tc-workers-*
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc-config:branch:master
    - grant:
        - docker-worker:capability:device:hostSharedMemory
        - docker-worker:capability:device:loopbackAudio
        - docker-worker:capability:privileged
        - queue:create-task:highest:proj-fuzzing/bugmon-monitor
        - queue:create-task:highest:proj-fuzzing/bugmon-processor
        - queue:get-artifact:project/fuzzing/bugmon/*
        - queue:route:notify.email.jkratzer@mozilla.com.on-failed
        - queue:scheduler-id:-
        - secrets:get:project/fuzzing/bz-api-key
      to:
        - hook-id:project-fuzzing/bugmon
