git-cinnabar:
  adminRoles:
    - login-identity:github/1038527|glandium
  repos:
    - github.com/glandium/git-cinnabar:*
  secrets:
    codecov: true
  workerPools:
    linux:
      imageset: generic-worker-ubuntu-22-04
      cloud: aws
      maxCapacity: 5
      instanceTypes:
        m5.xlarge: 1
    win2012r2:
      imageset: generic-worker-win2022
      cloud: aws
      maxCapacity: 2
      instanceTypes:
        c5.2xlarge: 1
        m5.2xlarge: 1
  clients:
    worker-osx:
      scopes:
        - assume:worker-pool:proj-git-cinnabar/osx
        - assume:worker-id:proj-git-cinnabar/travis-*
  grants:
    - grant:
        - queue:create-task:highest:proj-git-cinnabar/linux
        - queue:create-task:highest:proj-git-cinnabar/win2012r2
        # this workerType is implemented in Github Actions (!)
        - queue:create-task:highest:proj-git-cinnabar/osx
        - queue:scheduler-id:taskcluster-github
      to:
        - repo:github.com/glandium/git-cinnabar:decision-task

    - grant: assume:repo:github.com/glandium/git-cinnabar:decision-task
      to: repo:github.com/glandium/git-cinnabar:pull-request

    - grant:
        - assume:repo:github.com/glandium/git-cinnabar:decision-task
        - secrets:get:project/git-cinnabar/codecov
        - queue:route:index.project.git-cinnabar.*
      to:
        - repo:github.com/glandium/git-cinnabar:release
        - repo:github.com/glandium/git-cinnabar:release:*
        - repo:github.com/glandium/git-cinnabar:branch:*
        - repo:github.com/glandium/git-cinnabar:tag:*
