l10n:
  adminRoles:
    - github-team:mozilla-l10n/Core
  repos:
    - github.com/Pike/user-journey-localized:*
    - github.com/mozilla-l10n/*
  workerPools:
    ci:
      imageset: docker-worker-2021
      cloud: gcp
      maxCapacity: 5
  grants:
    - grant:
        - queue:create-task:highest:proj-l10n/*
      to:
        - repo:github.com/Pike/user-journey-localized:*
        - repo:github.com/mozilla-l10n/*
