mozci:
  adminRoles:
    - github-team:mozilla/compiler-and-development-tools
  repos:
    - github.com/mozilla/mozci:*
  workerPools:
    ci:
      owner: mcastelluccio@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 50
      workerConfig:
        dockerConfig:
          allowPrivileged: true
    compute-smaller:
      owner: mcastelluccio@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 25
      machineType: "zones/{zone}/machineTypes/n2-standard-2"
    compute-small:
      owner: mcastelluccio@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 25
      machineType: "zones/{zone}/machineTypes/n2-standard-4"
  secrets:
    testing: true
  grants:
    # all repos
    - grant:
        - queue:create-task:highest:proj-mozci/*
        - queue:route:statuses
      to:
        - repo:github.com/mozilla/mozci:*

    # all hooks
    - grant:
        - queue:scheduler-id:-
        - queue:create-task:highest:proj-mozci/*
      to: hook-id:project-mozci/*

    # Routes for mozci docker images
    - grant:
        - queue:route:index.project.mozci.docker-pr.*
        - queue:route:index.project.mozci.docker.*
      to: repo:github.com/mozilla/mozci:*

    - grant:
        # Allow decision task to create children tasks
        - queue:create-task:project:none

        # Children tasks are indexed
        - queue:route:index.project.mozci.*

        # Children tasks need to share a common cache
        - docker-worker:cache:mozci-classifications-testing

        # Children tasks read their configuration from taskcluster
        - secrets:get:project/mozci/testing
      to: hook-id:project-mozci/decision-task-testing

  hooks:
    decision-task-testing:
      description: Run mozci classification tasks for new pushes
      owner: mcastelluccio@mozilla.com
      emailOnError: true
      schedule: ['*/15 * * * *'] # every 15 minutes
      task:
        provisionerId: proj-mozci
        workerType: compute-smaller
        payload:
          image:
            type: indexed-image
            path: public/mozci.tar.zst
            namespace: project.mozci.docker.branch.master
          features:
            taskclusterProxy: true
          command:
            - decision
            - autoland
          maxRunTime: 1800
        scopes:
          - assume:hook-id:project-mozci/decision-task-testing
        metadata:
          name: mozci decision task - testing
          description: mozci decision task
          owner: mcastelluccio@mozilla.com
          source: https://github.com/mozilla/mozci
