# https://github.com/MasterWayZ is experimenting with TC workers and jobs
mwz:
  adminRoles:
    - login-identity:github/11596690|MasterWayZ
  externallyManaged:
    - "Secret=project/mwz/.*"
  workerPools:
    testing:
      owner: nobody@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
      machineType: "zones/{zone}/machineTypes/n1-standard-1"
