releng:
  adminRoles:
    - github-team:mozilla-releng/releng
  repos:
    - github.com/mozilla-releng/*
  workerPools:
    ci:
      owner: release@mozilla.com
      emailOnError: false
      imageset: generic-worker-ubuntu-22-04
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
  grants:
    - grant: queue:create-task:highest:proj-releng/*
      to: repo:github.com/mozilla-releng/*
