wpt:
  adminRoles:
    - github-team:web-platform-tests/admins
  workerPools:
    ci:
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 80
      workerConfig:
        dockerConfig:
          allowPrivileged: true
  repos:
    - github.com/web-platform-tests/*
  grants:
    - grant:
        - queue:create-task:highest:proj-wpt/ci
        - queue:create-task:highest:built-in/succeed
        - docker-worker:capability:privileged
        - queue:scheduler-id:taskcluster-github
      to:
        - repo:github.com/web-platform-tests/wpt:*
        - repo:github.com/web-platform-tests/wpt-tc-checks:*
