# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-worker-5nrfllxteqxz1yrln5kx
  aws:
    # originally built with the `docker_worker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0bd18568d25fa4852
      us-west-1: ami-0128d94ca859fcd2b
      us-west-2: ami-0123f65a860be84bb
      us-east-2: ami-07b28b1eb79e1dd6f
generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-00ff6399b9bbb217f
      us-west-1: ami-0a8fe9b46627594c6
      us-west-2: ami-0bc3827dc51b67d41
      us-east-2: ami-0afbf6fb4159ecf48
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/6141dcaa89185c9ef5a78147e706c3cabf638f86/imagesets/generic-worker-win2012r2/bootstrap.ps1
generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-01a043947fff1ba30
      us-east-2: ami-0881b64079821bf38
      us-west-1: ami-0a584dbd07adebae3
      us-west-2: ami-00ef635cda834ad6f
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/ac57dee9a0f6c5d20499df8f1ecbe29eda684ca7/imagesets/generic-worker-win2012r2-staging/bootstrap.ps1
  gcp:
    image: projects/taskcluster-imaging/global/images/generic-worker-win2012r2-staging-nx3g6xeg3iab95mb75sj
generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-04c680bf36e8a4283
      us-west-1: ami-08ba8312aa59cd7e4
      us-west-2: ami-0e1c81a83b28cf630
      us-east-2: ami-05d4f928c78c65e44
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bb0833bdce85dface0e0d6398a7d586fda9c9d8d/imagesets/generic-worker-ubuntu-18-04/bootstrap.sh
generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-062cab2cea2007391
      us-west-1: ami-0ff18eed48ac28e63
      us-west-2: ami-072a675238c3ac5b5
      us-east-2: ami-03e00d5b62ad9ea25
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/9032c610c6a70ee0b8729a39343b7b49bf1cf25a/imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh
relman-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0d835bc0f2d58c432
      us-west-1: ami-0c4c370afeb409a20
      us-west-2: ami-0cd6aa8e516c67ec9
      us-east-2: ami-0b292b91ab5b5f2eb
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: mcastelluccio@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/6141dcaa89185c9ef5a78147e706c3cabf638f86/imagesets/relman-win2012r2/bootstrap.ps1
generic-worker-win2016:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0aac8125d1c0c8b67
      us-west-1: ami-0a4ad1e015799dd17
      us-west-2: ami-01f9b70cbfa383c57
      us-east-2: ami-0db37aad2e293244d
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/6141dcaa89185c9ef5a78147e706c3cabf638f86/imagesets/generic-worker-win2016/bootstrap.ps1
generic-worker-ubuntu-20-04-staging:
  workerImplementation: generic-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/generic-worker-ubuntu-20-04-staging-qcptgq686i8olmysjhvx
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/14567b55185a5a9f57b72b8469cb1edda19097c4/imagesets/generic-worker-ubuntu-20-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-0ede578806a746f82
      us-west-2: ami-0412520122ad3f21b
      us-east-1: ami-09b4a9570e5de9e11
      us-east-2: ami-0c06727d5bd02f891
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-1: ami-08d7566866a6f6b92
      us-west-2: ami-04979e6be3c3dc7b5
      us-east-1: ami-02e5df2c6cc595f33
      us-east-2: ami-011d7ffb17c0848e6
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/6141dcaa89185c9ef5a78147e706c3cabf638f86/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2016-amd:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-2: ami-0a00428b948b5eb4c
      us-east-1: ami-03c1676c91062ae05
      us-east-2: ami-050585a75ea3c5851
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: jkratzer@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/5b19644c4c63d6ee9723c5166dcb56ebce382a7d/imagesets/generic-worker-win2016-amd/bootstrap.ps1
