# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-worker-5nrfllxteqxz1yrln5kx
  aws:
    # originally built with the `docker_worker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0bd18568d25fa4852
      us-west-1: ami-0128d94ca859fcd2b
      us-west-2: ami-0123f65a860be84bb
      us-east-2: ami-07b28b1eb79e1dd6f
generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-07d683fa39bbeda64
      us-west-1: ami-0bb00e94d8edaaa46
      us-west-2: ami-0134f14c5d00e0512
      us-east-2: ami-0b4ff1dc19cc7d266
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/18f1db7d8bab25f5110cf348ea82cefa6ad4cac5/imagesets/generic-worker-win2012r2/bootstrap.ps1
generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-01a043947fff1ba30
      us-east-2: ami-0881b64079821bf38
      us-west-1: ami-0a584dbd07adebae3
      us-west-2: ami-00ef635cda834ad6f
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/ac57dee9a0f6c5d20499df8f1ecbe29eda684ca7/imagesets/generic-worker-win2012r2-staging/bootstrap.ps1
  gcp:
    image: projects/taskcluster-imaging/global/images/generic-worker-win2012r2-staging-nx3g6xeg3iab95mb75sj
generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-04c680bf36e8a4283
      us-west-1: ami-08ba8312aa59cd7e4
      us-west-2: ami-0e1c81a83b28cf630
      us-east-2: ami-05d4f928c78c65e44
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bb0833bdce85dface0e0d6398a7d586fda9c9d8d/imagesets/generic-worker-ubuntu-18-04/bootstrap.sh
generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-062cab2cea2007391
      us-west-1: ami-0ff18eed48ac28e63
      us-west-2: ami-072a675238c3ac5b5
      us-east-2: ami-03e00d5b62ad9ea25
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/9032c610c6a70ee0b8729a39343b7b49bf1cf25a/imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh
relman-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-02232f2d413960ac8
      us-west-1: ami-0250a41d54c92ef34
      us-west-2: ami-0ad42b9ed6e00ed79
      us-east-2: ami-03390fb2d21cafffb
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: mcastelluccio@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/18f1db7d8bab25f5110cf348ea82cefa6ad4cac5/imagesets/relman-win2012r2/bootstrap.ps1
generic-worker-win2016:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0013a6f54841d0b20
      us-west-1: ami-0bb7bd2c95efd377a
      us-west-2: ami-0f58b2394da254988
      us-east-2: ami-093fb6260f9b65d29
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/18f1db7d8bab25f5110cf348ea82cefa6ad4cac5/imagesets/generic-worker-win2016/bootstrap.ps1
generic-worker-ubuntu-20-04-staging:
  workerImplementation: generic-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/generic-worker-ubuntu-20-04-staging-emac14z9wq3qcjaqb5ui
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/ae6d3d17f01b775f37622f9ff97a06b5f22fe8b5/imagesets/generic-worker-ubuntu-20-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-0ede578806a746f82
      us-west-2: ami-0412520122ad3f21b
      us-east-1: ami-09b4a9570e5de9e11
      us-east-2: ami-0c06727d5bd02f891
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-1: ami-0f82e5574dcbf8407
      us-west-2: ami-0dd9f06207e4cd4a7
      us-east-1: ami-0450dd620727608bf
      us-east-2: ami-044208244a191d93c
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/18f1db7d8bab25f5110cf348ea82cefa6ad4cac5/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2016-amd:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-2: ami-066d37e7817c77ce4
      us-east-1: ami-00f011e619ad67213
      us-east-2: ami-0ff4619b4f38042e1
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: jkratzer@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/18f1db7d8bab25f5110cf348ea82cefa6ad4cac5/imagesets/generic-worker-win2016-amd/bootstrap.ps1
