# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-worker-5nrfllxteqxz1yrln5kx
  aws:
    # originally built with the `docker_worker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-09933aeacc9b3c2ba
      us-west-1: ami-036c57fcae9304ec3
      us-west-2: ami-090b3bb7401689d98
generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0ea2d6a26ba0ffde7
      us-west-1: ami-0959b4998c8c0ab44
      us-west-2: ami-0a1f50b64461e4bd1
      us-east-2: ami-0cce10fe69638bea3
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/9d7b1fc713547a014abe04397ba378bdc6d8221e/imagesets/generic-worker-win2012r2/bootstrap.ps1
generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0fb95ec4bb2677a13
      us-east-2: ami-0bdc0ff4f7b2668a3
      us-west-1: ami-03571e89c6f39469a
      us-west-2: ami-0feccd5a7c9fb3d5d
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/7912ef2b182c29eac6cd18f7a42b7ddb37e7a3e0/imagesets/generic-worker-win2012r2-staging/bootstrap.ps1
generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0db16a1eab5d7ee12
      us-west-1: ami-0a3634204ccf6dc1f
      us-west-2: ami-0aa6f5734514fd189
      us-east-2: ami-0c57aa42e00e4410a
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/5611dfd9817937dc741df5df2a231257f7fd5ad9/imagesets/generic-worker-ubuntu-18-04/bootstrap.sh
generic-worker-ubuntu-18-04-podman:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0f7922d839c6778ce
      us-west-1: ami-0d15d84d0d3c0c05e
      us-west-2: ami-0224758e5b048b961
      us-east-2: ami-0a0d2a9f8d222630d
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/5611dfd9817937dc741df5df2a231257f7fd5ad9/imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh
generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0676d665caff00630
      us-west-1: ami-0ca7d5b2ec1c971ea
      us-west-2: ami-089a3e8c95386bb90
      us-east-2: ami-01bf7c2a1d7894fc7
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/221899853f2c4e09c97b92e1e2e53e889a668bd2/imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh
relman-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-063ee810ed871c794
      us-west-1: ami-0c815afcc14eae4d7
      us-west-2: ami-03e882fa91a05d124
      us-east-2: ami-087be40c34f10f2e0
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: mcastelluccio@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/5611dfd9817937dc741df5df2a231257f7fd5ad9/imagesets/relman-win2012r2/bootstrap.ps1
generic-worker-win2016:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-02bcfc9a24751f1bb
      us-west-1: ami-00f8f353a4a4055d4
      us-west-2: ami-0e019740238f6f1fd
      us-east-2: ami-03fd7c33256729351
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/5611dfd9817937dc741df5df2a231257f7fd5ad9/imagesets/generic-worker-win2016/bootstrap.ps1
