# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-community-gcp-googlecompute-2022-12-14t16-52-34z
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-03f1c0a7102c03856
      us-east-2: ami-0a172d261610275a8
      us-west-1: ami-079635988fff55b09
      us-west-2: ami-08c278b93b0349b65
# v44.23.4 docker worker which includes the disableSeccomp feature
docker-worker-legacy:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-community-gcp-googlecompute-2022-12-19t19-01-04z
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0ec6d5fc54628fa9b
      us-east-2: ami-071b3ff08f2d9c1dd
      us-west-1: ami-03f677a21b2fadb15
      us-west-2: ami-0de87470eb34a8e36
relman-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-043f20b9d24912704
      us-west-1: ami-025c77d7158d86739
      us-west-2: ami-0c5fc166a6180a86a
      us-east-2: ami-049d92d455adda565
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: mcastelluccio@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/eb8ea65f619e0808342acf94742f81dab3750fe1/imagesets/relman-win2012r2/bootstrap.ps1
generic-worker-ubuntu-22-04:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/cda67218ac1df618204294b14d671fcb1c177401/imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-0cb4891e7c3468896
      us-west-2: ami-0fb25a15eb7573994
      us-east-1: ami-07be1615279fe11d3
      us-east-2: ami-018e5239fd5c0ad02
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-0tjqrcuyegnoqshxd40o
generic-worker-ubuntu-22-04-staging:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/ca97a7fc473a293282c17f55aa7882e7b4e8857f/imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-0b85253ec5b8ddc87
      us-west-2: ami-019c7bdb181967cdd
      us-east-1: ami-0b6b1747aaf90df9b
      us-east-2: ami-08b182be4387c2600
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-staging-e4k6zz5w813o26vibjyx
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-1: ami-0944046876d6ef63a
      us-west-2: ami-057b304c90034602e
      us-east-1: ami-0a35edfbbe9458b00
      us-east-2: ami-0375161d5244b57f8
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/6bb44db56edc7e6410c7e83011c23b8a0fc691be/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2016-amd:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-2: ami-066d37e7817c77ce4
      us-east-1: ami-00f011e619ad67213
      us-east-2: ami-0ff4619b4f38042e1
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: jkratzer@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/18f1db7d8bab25f5110cf348ea82cefa6ad4cac5/imagesets/generic-worker-win2016-amd/bootstrap.ps1
