# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-worker-5nrfllxteqxz1yrln5kx
  aws:
    # built with the `docker_worker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-09933aeacc9b3c2ba
      us-west-1: ami-036c57fcae9304ec3
      us-west-2: ami-090b3bb7401689d98
generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0e62fbaf25d83c44b
      us-west-1: ami-0958b2c69b4ed2611
      us-west-2: ami-06e878f5fa9fc3ad0
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-win2012r2/bootstrap.ps1
generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0645f31a90010e574
      us-west-1: ami-01ecc4a44b76f7863
      us-west-2: ami-0f984fd4c43810fe0
      us-east-2: ami-042978a5ec2271521
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/0037422535df55cf1d66ba744af6d800bd48fbd0/imagesets/generic-worker-win2012r2-staging/bootstrap.ps1
generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-01bd01b28254e5a56
      us-west-1: ami-02e4b726d0345d08d
      us-west-2: ami-0ba12100c15b123a9
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-ubuntu-18-04/bootstrap.ps1
generic-worker-ubuntu-18-04-podman:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-007d2656f20ae9682
      us-west-1: ami-0128237e2d2dd20f9
      us-west-2: ami-0f8273badc7fa90eb
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.ps1
generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0bfbcea1e13dfdb8a
      us-west-1: ami-0b9d053fd6a809c8c
      us-west-2: ami-0f402ebee06e1d5c9
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.ps1
relman-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0d519e139a6978570
      us-west-1: ami-0c3f17137c65cacfa
      us-west-2: ami-08960f888353c602b
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: mcastelluccio@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/main/imagesets/relman-win2012r2/bootstrap.ps1
generic-worker-win2016:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0f5ccb6ced36218ac
      us-west-1: ami-0568d4a6cc3448751
      us-west-2: ami-0e1abf242b85887d0
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/c8d4c4047008cdb1787edba19f526c619b82cae7/imagesets/generic-worker-win2016/bootstrap.ps1
