# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/community-tc-workers/global/images/docker-worker-06zh2jnsaud6lidlb226
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0dec39d7aada81074
      us-east-2: ami-092b8b27bd19354b1
      us-west-1: ami-00a820994ea4f2436
      us-west-2: ami-0c01795c91ab91152
# v44.23.4 docker worker which includes the disableSeccomp feature
docker-worker-legacy:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-community-gcp-googlecompute-2022-12-19t19-01-04z
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0ec6d5fc54628fa9b
      us-east-2: ami-071b3ff08f2d9c1dd
      us-west-1: ami-03f677a21b2fadb15
      us-west-2: ami-0de87470eb34a8e36
generic-worker-freebsd:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/ce90750aa55ab27f6111040925ebe820ec939ff0/imagesets/generic-worker-freebsd/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-03ab357e5bc4fde14
      us-west-2: ami-0aec17d43bf888035
      us-east-1: ami-05904e574e7a66fa8
      us-east-2: ami-090ed2386963df7bf
generic-worker-ubuntu-22-04:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/0967e581c4fa4457fe7cd752ffc114e4d0b0d3c4/imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-kzcagf1do6zgav3crq26
  aws:
    amis:
      us-west-1: ami-0eb17464e578b44d5
      us-west-2: ami-02a7270b55dd946f5
      us-east-1: ami-011048e0d4537b83c
      us-east-2: ami-0a0ebf8405f687574
generic-worker-ubuntu-22-04-arm64:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/a9aebb8e90adb515d03708d2a9a9f6d514a57f1b/imagesets/generic-worker-ubuntu-22-04-arm64/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-arm64-ncwkicpm98m2zgpygqh5
generic-worker-ubuntu-22-04-staging:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: false
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/0610499d5683ae9e1b923f5fbb3f449399466ba6/imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-00cbf2383cdbbed1c
      us-west-2: ami-095d5725945be2976
      us-east-1: ami-083fb9890e92fd30f
      us-east-2: ami-07cee45c90d0d96bc
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-staging-xgg92i5sy64yzgy9w91d
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0fc88c52a68129bc1
      us-west-1: ami-08b787adab09702ef
      us-west-2: ami-0fe303ecd7239bc1e
      us-east-2: ami-0e5c9b6a8dd69a471
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/293f6cdefec747dfc216eeaabe54cd65766ffca3/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2016-amd:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-2: ami-0a3fed6d5ad828515
      us-east-1: ami-03fe23d6fab43a676
      us-east-2: ami-0e09db127701ab69e
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: jkratzer@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/2a6c7855e9d4ee85e0c12ba61158e3f0fce64673/imagesets/generic-worker-win2016-amd/bootstrap.ps1
