# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    # built with the `docker_worker_gcp_community` builder in monopacker
    image: projects/taskcluster-imaging/global/images/docker-worker-gcp-community-googlecompute-2020-06-12t17-25-46z
  aws:
    # built with the `docker_worker_aws` builder in monopacker
    amis:
      us-east-1: ami-005cff3ff8491780e
      us-west-1: ami-0ce5b2d9acbd9b924
      us-west-2: ami-0dd3c7aae136f0a60
generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0e62fbaf25d83c44b
      us-west-1: ami-0958b2c69b4ed2611
      us-west-2: ami-06e878f5fa9fc3ad0
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-win2012r2/bootstrap.ps1
generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0fd523d8ec2760438
      us-west-1: ami-0f8c5f3dfe823981b
      us-west-2: ami-009a9df1928a7c91c
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/d783d4128337c16f25a7be4eb6536f5a64d4d669/imagesets/generic-worker-win2012r2-staging/bootstrap.ps1
generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-01bd01b28254e5a56
      us-west-1: ami-02e4b726d0345d08d
      us-west-2: ami-0ba12100c15b123a9
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-ubuntu-18-04/bootstrap.ps1
generic-worker-ubuntu-18-04-podman:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-007d2656f20ae9682
      us-west-1: ami-0128237e2d2dd20f9
      us-west-2: ami-0f8273badc7fa90eb
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.ps1
generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0bfbcea1e13dfdb8a
      us-west-1: ami-0b9d053fd6a809c8c
      us-west-2: ami-0f402ebee06e1d5c9
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.ps1
deepspeech-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0c5cea59ad500f24f
      us-west-1: ami-09261ce2c40527cc4
      us-west-2: ami-0d97c9d49aaed6e19
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/deepspeech-win2012r2/bootstrap.ps1
deepspeech-win2012r2-b:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0278191232a1beec3
      us-west-1: ami-091da09481078cd8f
      us-west-2: ami-0dd58442a534e696b
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/99e12476a6555a147c218407dfcef82e1d1a7f82/imagesets/deepspeech-win2012r2-b/bootstrap.ps1
deepspeech-win2012r2-gpu:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0a61f644615594e90
      us-west-2: ami-0e917d503a92d04af
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/deepspeech-win2012r2-gpu/bootstrap.ps1
deepspeech-win2012r2-gpu-b:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-04245d88ef5f32b85
      us-west-2: ami-01a6caff9a80fccfd
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/deepspeech-win2012r2-gpu-b/bootstrap.ps1
generic-worker-win2016:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0804934b530c176ec
      us-west-1: ami-0064e0c8eaea8b432
      us-west-2: ami-0eadb98acb7628735
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/bdb75beb514c89526422ee45a3de2f421a12c92e/imagesets/generic-worker-win2016/bootstrap.ps1
